name: investsuite_server
description: gRPC server for InvestSuite portfolio data
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  grpc: ^5.1.0
  protobuf: ^6.0.0
  http: ^1.6.0
  fixnum: ^1.1.1
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^5.0.0

